### ISSUE TITLE
System.ComponentModel.Annotations version mismatch error. 

### ISSUE THREAD

**Issue by rbflow** [StefH/System.Text.Json.EnumExtensions#2]
Hi I'm receiving this error after upgrading to 5.0.0.0. I put a binding redirect however it doesn't work still. Can you please upgrade your project to use the latest version of this dll?

Could not load file or assembly 'System.ComponentModel.Annotations' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.IO.FileLoadException: Could not load file or assembly 'System.ComponentModel.Annotations' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Assembly Load Trace: The following information can be helpful to determine why the assembly 'System.ComponentModel.Annotations' could not be loaded.

**Comment by StefH** [comment]
Dear @rbflow ,

I can add `netstandard2.1` as framework and require version 5.0.0, will that help you?

**Comment by StefH** [comment]
https://github.com/StefH/System.Text.Json.EnumExtensions/pull/3

**Comment by StefH** [comment]
New version 1.0.1 will be released soon which also targets netstandard2.1 and net5.0
