### ISSUE TITLE
Serialize as int, but allow deserialization as "0", "1"

### ISSUE THREAD

**Issue by benmccallum** [StefH/System.Text.Json.EnumExtensions#5]
In our transition over from Newtonsoft, I've noticed it was able to handle string representations of the numeric enum value so in some cases our client got away with passing that and in order to facilitate a smooth transition we want to try maintain that behaviour.

With this converter setup I believe sending "0" is working and being deserialized, but then everything serializes as a string, whereas I'd like it to still be an `int`.

This is more of an FYI than anything else as I will likely just whip up a custom converter and factory for our particular case that wraps the default one, but thought I'd mention it as a feature you could add if you like.

**Comment by StefH** [comment]
Thanks for the information. However this new functionality does not really belong in this project, because this library specifically deals with enums.

**Comment by benmccallum** [comment]
For anyone who lands here looking for a solution I created a custom serializer that does the job. [Here's a gist](https://gist.github.com/benmccallum/84ce901122133335ec195e9a62da03b4).
